* adjust: 废弃了bookworm-run-root，重制了bookworm-run以提升代码质量
* fix: 部分应用卸载失败的问题

* fix: 光标主题失效的问题

diff --git a/src/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/ace-uninstall-helper b/src/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/ace-uninstall-helper
--- a/src/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/ace-uninstall-helper
+++ b/src/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/ace-uninstall-helper
@@ -25,8 +25,13 @@ fi
 
 # 验证是否为desktop文件
 if [[ ! $ABSOLUTE_PATH == *.desktop ]]; then
-    echo "Error: The file is not a desktop file."
-    exit 1
+	if [ ! -e $ABSOLUTE_PATH ];then
+		echo "$ABSOLUTE_PATH does not exist. May have already been uninstalled. Ignore it."
+		exit
+	else
+    		echo "Error: The file is not a desktop file."
+    		exit 1
+	fi
 fi
 
 # 截取路径
